chunk_size: 256
local_device: null
remote_url: "redis-sentinel://localhost:26379,localhost:26380,localhost:26381"
remote_serde: "cachegen"

# Whether retrieve() is pipelined or not
pipelined_backend: False

# Whether saving decode KV cache to boost multi-turn conversation or not
save_decode_cache: True
