chunk_size: 256
local_device: null
remote_url: "lm://localhost:65431"
remote_serde: "safetensor"

# Whether retrieve() is pipelined or not
pipelined_backend: False

# Whether saving decode KV cache to boost multi-turn conversation or not
save_decode_cache: True
