chunk_size: 256
local_device: "cpu"

# Whether retrieve() is pipelined or not
pipelined_backend: False

# Whether the prefill requests can be chunked based on the max_num_batched_tokens or not
enable_chunked_prefill: True